apiVersion: messaging.knative.dev/v1beta1
kind: InMemoryChannel
metadata:
  name: wr-fw-channel
  namespace: log-replayer
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: wr-reply-service
  namespace: log-replayer
spec: 
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - image: mbrouns/event_reply:v1
---
apiVersion: messaging.knative.dev/v1beta1
kind: Subscription
metadata:
  name: wr-ad-channel-subscription
  namespace: log-replayer
spec:
  channel:
    apiVersion: messaging.knative.dev/v1beta1
    kind: Channel
    name: ad-channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: wr-reply-service
  reply:
    ref:
      apiVersion: messaging.knative.dev/v1beta1
      kind: InMemoryChannel
      name: wr-fw-channel
---
apiVersion: messaging.knative.dev/v1beta1
kind: Subscription
metadata:
  name: wr-fw-channel-inferenceservice-subscription
  namespace: log-replayer
spec:
  channel:
    apiVersion: messaging.knative.dev/v1beta1
    kind: InMemoryChannel
    name: wr-fw-channel
  subscriber:
    ref:
      apiVersion: serving.kubeflow.org/v1alpha2
      kind: InferenceService
      name: wr-inferenceservice
---
apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  name: wr-inferenceservice
  namespace: log-replayer
spec:
  default:
    predictor:
      custom:
        logger:
          mode: all
        container:
          image: wroosmalen/kubeflow-ad-bidding:0.12
          name: kfserving-container
          env:
          - name: MODEL_STORAGE_PATH
            value: model.pickl
---
apiVersion: messaging.knative.dev/v1beta1
kind: Subscription
metadata:
  name: wr-fw-channel-sink-subscription
  namespace: log-replayer
spec:
  channel:
    apiVersion: messaging.knative.dev/v1beta1
    kind: InMemoryChannel
    name: wr-fw-channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: wr-sink
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: wr-sink
  namespace: log-replayer
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - image: mbrouns/event_sink:v1