apiVersion:  v1
kind: Pod
metadata:
  name: kubeflow-bandit-wouter
  namespace: log-replayer
spec:
  volumes:
    - name: data
      emptyDir: {}
  containers:
  - name: kubeflow-bandit-wouter
    image: wroosmalen/kubeflow-bandit:0.06
    env:
    - name: REDIS_HOST
      value: "kubeflow-bandit-redis"
  - name: kubeflow-bandit-wouter-redis
    image: redis:6.2.3
    command:
    - redis-server
    ports:
    - containerPort: 6379
    volumeMounts:
    - mountPath: /data
      name: data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    application: kubeflow-bandit-wouter
  name: kubeflow-bandit-wouter-redis
  namespace: log-replayer
spec:
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    application: kubeflow-bandit-wouter
  type: ClusterIP