apiVersion:  apps/v1
kind: Deployment
metadata:
  name: kubeflow-bandit-wouter
  namespace: log-replayer
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kubeflow-bandit-wouter
  template:
    metadata:
      labels:
        application: kubeflow-bandit-wouter
    spec:
      containers:
      - name: kubeflow-bandit-wouter
        image: wroosmalen/kubeflow-bandit:0.07
        env:
        - name: REDIS_HOST
          value: "kubeflow-bandit-wouter-redis"
---
apiVersion:  apps/v1
kind: Deployment
metadata:
  name: kubeflow-bandit-wouter-redis
  namespace: log-replayer
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kubeflow-bandit-wouter
  template:
    metadata:
      labels:
        application: "kubeflow-bandit-wouter"
    spec:
      containers:
      - name: kubeflow-bandit-wouter-redis
        image: redis:6.2.3
        args: ["--appendonly", "yes", "--save", "900", "1", "--save", "30", "2"]
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
      - name: data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    application: kubeflow-bandit-wouter
  name: kubeflow-bandit-wouter-redis
  namespace: log-replayer
spec:
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    application: kubeflow-bandit-wouter
  type: ClusterIP